{ config, lib, pkgs, modulesPath, ... }:

{
  # ==========================================
  # IMPORTANT: REPLACE THIS CONTENT
  # ==========================================
  # usage:
  # cp /etc/nixos/hardware-configuration.nix ./hosts/v110/hardware-configuration.nix
  #
  # This file is auto-generated by 'nixos-generate-config'
  # It contains the fileSystems config and specific kernel modules for your hardware.
  
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
    };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
